version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./definitions.json:/tmp/definitions.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/definitions.json"
    networks:
      - communication-network

  server:
    depends_on:
      - rabbitmq
    restart: always
    container_name: communication-microservice-backend
    image: communication-microservice-backend:latest
    build: 
      context: .
      dockerfile: server/docker/Dockerfile
    expose:
      - 8000
    networks:
      - communication-network

  nginx:
    restart: always
    container_name: communication-microservice-nginx
    image: communication-microservice-nginx:latest
    build:
        context: ./nginx
        dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - communication-network

volumes:
  rabbit_data:

networks:
  communication-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16