apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
  labels:
    {{- include "communication.labels" . | nindent 4}}
    app.kubernetes.io/component: communication
spec:
  replicas: {{ .Values.communication.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: communication
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: communication
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: communication
          image: {{ .Values.communication.image }}
          ports:
            - name: http
              containerPort: 15672
              protocol: TCP
            - name: amqp
              containerPort: 5672
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 15672
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 15672